In [2]:
#using for loop  manually adding values
from numpy import *
arr=array([1,2,3,4,5])
for i in arr:
    i=i+5
    print(i)

6
7
8
9
10


In [3]:
#simple way to add by module
from numpy import *
arr=array([1,2,3,4,5])
ar=arr+5                # simple way to add just by importing numpy
print(ar)

[ 6  7  8  9 10]


In [4]:
#addining two array 
from numpy import *
a1=array([1,2,3,4,5])
a2=array([6,7,8,9,10]) #adding two array knows as vectorized operation
a3=a1+a2         # simple way to add 2 array
print(a3)   #printing two array

[ 7  9 11 13 15]


In [7]:
#numpy provide many predefine function to perform certain operation
from numpy import *

a1=array([1,2,3,4,5]) 
#print (log(a1))# to find the log of the number
#print(sin(a1))# sin VAlues 
print(sqrt(a1))# square root of number

[1.         1.41421356 1.73205081 2.         2.23606798]


In [9]:
from numpy import *

a1=array([1,2,3,4,5,8,7])
print (sort(a1))# we can directly sort the array

[1 2 3 4 5 7 8]


In [13]:
from numpy import *

a1=array([1,2,3,4,5,5,8,23,23,7])
print (unique(a1))# does not allowed the duplicate

[ 1  2  3  4  5  7  8 23]


In [17]:
 a3=(a1,a2)               # we can concatenate two array
print(a3)

(array([ 1,  2,  3,  4,  5,  5,  8, 23, 23,  7]), array([ 6,  7,  8,  9, 10]))


# we can concatenate two array

In [19]:
a3=concatenate([a1,a2])        # added two array together
print(a3)

[ 1  2  3  4  5  5  8 23 23  7  6  7  8  9 10]


In [28]:
# assigning one array to another array
a1=array([2,3,4,5])

a2=a1
print(a1)
print(a2) 
#but the memory allocation addres is same to both the array because the both array holding the same memory adddress
print(id(a1))
print(id(a2))

[2 3 4 5]
[2 3 4 5]
140574485775424
140574485775424


In [29]:
# view() is a function which will help to create two array with same values but with different memory address
from numpy import *
a1=array([2,3,4,5])
a2=a1.view()
print(a1)
print(a2) 
print(id(a1))
print(id(a2))   #same values with different memory addres using view()function

[2 3 4 5]
[2 3 4 5]
140574485777904
140574485258368


In [30]:
#there are two way by which you can copy the element of array
#1)shallow:in this array one array is depended on another array mean i change the values of one array than it automatically reflect the second array

#2)deep:no one is depend on any other array .value is independent
#shallow
a=array([1,2,3,4,5])
a2=a
a[1]=3   #changed the values of array of index 1 , 
print(a)
print(a2)# changes took places in both array

[1 3 3 4 5]
[1 3 3 4 5]


In [32]:
# deep
a=array([1,2,3,4,5])
a2=a.copy()# copy is method which we will create the copy of a
a[1]=3    #
print(a)  #changing will takeplace on first array
print(a2) #it will remain the same  because we have used copy function

[1 3 3 4 5]
[1 2 3 4 5]
