In [4]:
from numpy import *
arr=array([
    [1,2,3,4],
    [5,6,7,8]
    
])
print(arr)#printing 2dim array


[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#prebuild method to print the dimension of array
print(arr.ndim)  #used to find the dimension of array

2


In [14]:
#shape  it will give the numbers of rows and column
print(arr.shape)   #means with 2 rows and 3 column

(2, 4)


In [15]:
#size it willgive the size of array
print(arr.size) #size of array

8


In [19]:
# to convert 2d array to single array !it means to convert 2d array in 1 line
arr2=arr.flatten()# flatten method call on arr and the values is stored in arr2 
print(arr2)

[1 2 3 4 5 6 7 8]


In [24]:
# to convert from 1d array to 2 or 3d array
ar=arr2.reshape(2,3)   #reshape is used to convert it into 2 or 3 dimentional array
#(no.of rows,no. of column)
print(ar)

[[1 2 3]
 [4 5 6]]


In [35]:
#arr2.extend([10,20,30,40])

AttributeError: 'numpy.ndarray' object has no attribute 'extend'

In [37]:
arr=array([
    [2,3,4,5],
    [7,8,9,10]
])
print(arr)

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [48]:
arr.flatten()   # to convert it into one dimentionsal array

array([ 2,  3,  4,  5,  7,  8,  9, 10])

In [49]:
arr.reshape(2,4)  # total 8 values means we can make 2*4 ratio

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [51]:
arr.ndim  # it a method to find the size of array

2

# toconvert array into matrix

In [58]:
#there is a function matrix which will convert array to matrix
print(type(arr))# now it in array format
print(arr.dtype)  #it is int type array
 #to convert array to matrix
c=matrix(arr)
print(c) #converted into matrix
    

<class 'numpy.ndarray'>
int64
[[ 2  3  4  5]
 [ 7  8  9 10]]


# to define a matrix


In [65]:
yuvi=matrix('2,3,4,5;2,3,4,5;2,3,4,5')   #declaration of array using matrix function
print(yuvi)

[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]


# to print matrix diagonal values

In [81]:
# if we want to print the diagonal element or number we can use diagonal function
yahoo=matrix('1,2,3,4;5,6,7,8;10,11,12,13')
print(yahoo)
 #now i just want to print the diagonal number
print(diagonal(yahoo)) #here it will print all the diagonal number

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]
[ 1  6 12]


# addining two matrix

In [92]:
yo=matrix('1,2,3;4,5,6')
yo1=matrix('7,8,9;1,2,3')
add=yo+yo1
print(add)

[[ 8 10 12]
 [ 5  7  9]]


# multiplication of two matrix using prebuild function

In [98]:
m1=matrix('1,2,3;2,3,4')
m2=matrix('1,2;2,3;4,5')
mul=m1*m2  
# for multiplication of matrix there are some basix rules that we have to follows
#rule no 1:
#the multiplication is only possible when the 1st matrix no of column is same as 2nd matrix no. of rows
# the result of matrix will be on the bases of 1 matrix row = 2nd matrix no of column
print(mul)

[[17 23]
 [24 33]]


In [116]:
 #multiplicATION OF TWO MATRIX MANUALLY
from numpy import *
a1=matrix('1,2,3;1,2,3')
a2=matrix('2,1;1,2;1,2')
#mul=a1*a2
result =[[0,0],[0,0]]
            
for i in range(len(a1)):
    for j in range(len(a2[0])):
        for k in range(len(a2)):
            result[i][j]=result+a1[i][k] * a2[k][j]
for r in result:  
     print(r) 

ValueError: shapes (1,3) and (1,2) not aligned: 3 (dim 1) != 1 (dim 0)

In [12]:
X = [[1,2,3],  
    [4,5,6],  
    [7,8,9]]  
 
Y = [[10,11,12],  
      [13,14,15],  
      [16,17,18]]  
 
result = [[0,0,0],  
               [0,0,0],  
              [0,0,0]] 
for i in range(len(X)):  
    #print(i)# define the number of rows
    for j in range(len(Y[0])):  
    
        for k in range(len(Y)):  
            result[i][j] += X[i][k] * Y[k][j]  # firts []  decide the rows n [] second column
for r in result:  
     print(r)  

[84, 90, 96]
[201, 216, 231]
[318, 342, 366]
