# way to create array in numpy

1)array 2)linspace() 3)logspace() 4)arange() 5)zeros() 6)ones()

# array

In [14]:
from numpy import *
arr=array([1,2,3,4])# no need to specify the typecode(datatype) of array
print(arr.dtype)# it will check the datatype of array

int64


In [13]:
from numpy import *#using numpy removing the number on the bases of index number
arr=array([1,2,3,56])
print(arr)
c=0
user=int(input("enter the index number"))
for i in arr:#here the value of arr(array)will be assigned to i not the index number:
    if(c==user):#if block execute the condition 
        c=c+1
        continue
    else:
        print(i)#printing 
        c=c+1  #it will increment the value of c after that it wil again cal for loop because the loop repeate not the if else condition

[ 1  2  3 56]
enter the number2
1
2
56


In [19]:
# using numoy we can assign different type of value to array
from numpy import *
b=array([10,20,30,40,50.45])#here i used a float value with integer
print(b.dtype)# so wil check the datattype
print(b)#printed the values in the formof float


float64
[10.   20.   30.   40.   50.45]


In [21]:
from numpy import *
b=array([10,20,30,40,50.45],int)#we can specify which type datatype we want so that we can print 
print(b.dtype)# 
print(b)#printed

int64
[10 20 30 40 50]


# linspace

In [45]:
#it take 3 argument 1.starting point ,ending point n 3 is used to tell how many parts u wants that number should divided
a= linspace(0,15,16)# linspace with 3 argument
print(a)
#printing the values

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [47]:
#but if we dont specify the 3 element so by defalt it will take 50 
a=linspace(0,15)# linspace with 3 argument
print(a)

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [28]:
from numpy import *
a=linspace(0,10,2)# so it will start from 0 and end at 10 but as we had specify it will divide into 2 parts
print(a)

[ 0. 10.]


# Arange


In [30]:
c=arange(1,20,3)# so it start from 1 and end at 20 and the 3 argument which it will take will decide the difference between number
print(c)#eg=1+3=4,4+3=7,7+3=10 ...

[ 1  4  7 10 13 16 19]


# logspace

In [31]:
#it 3 argument .same as linspace but in the ratio of 10
c=logspace(1,40,5)# it will print in the form of log that is in the raised of 10 measn 10e(10 raised to number)
print(c)# it will divide in 5 parts but in the ratio of 10

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


# zeros()

In [35]:
#zero ,if we want to create a array but the values should be zero at that time we can use this:
#a=zeros(5)# it take only 1 values
a=zeros(5)#here i have declare 5 it mean it will make a array of size 5
print(a)

[0. 0. 0. 0. 0.]


# ones()

In [42]:
from numpy import *
a=ones(10)# it same as zeros it wil create a array of size 10 but the values will be 1 for all
print(a)
#print(a.dtype())

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
