In [ ]:
def fun(**a):  # keyworad variable length argument
    #print(a)
    for i, j in a.items():
        print(i,j)
fun(schnlname='clms',number='20',add='chandan naka')

In [32]:
from numpy import *
a=array([1,2,3,4],int)
d=a.reshape(2,2)
b=a.view()  # dependent array
#print(b)
#b[0]=10
c=a.copy()   # independent array
c[1]=200


[1 2 3 4]


In [12]:
print(d)
e=matrix(d) #converting to matrix

[[1 2]
 [3 4]]


In [14]:
print(e)
type(e)

[[1 2]
 [3 4]]


numpy.matrix

In [15]:
# copy array using typecode

In [18]:
from array import array
arr=array('i',[1,2,3,4,5])
newcopy=array(arr.typecode,[newcopy for newcopy in arr])  # g esmai arr ka value newcopy mai jayega and uske baad newcopy mai assign hoga
print(newcopy)# got the output

array('i', [1, 2, 3, 4, 5])


In [41]:
li=[1,2,3,3,4,4,2,45,60] # finding unique element in a list
new=dict.fromkeys(li)# dictionary mai convert karenge,agar set mai convert kia toh index value mai chanages hoga
print(new) 

{1: None, 2: None, 3: None, 4: None, 45: None, 60: None}


In [45]:
list(new)  # then convert it to list and get the unique element


[1, 2, 3, 4, 45, 60]

In [51]:
a="deepak"
for i in range(len(a)-1,0-1,-1):  #  using loop we will reverse
    print(a[i])

k
a
p
e
e
d


In [52]:
# direct reverse using slicing
a='deepak'
a[::-1]

'kapeed'

In [55]:
a='ancd'[0]  # if we want any specific number
print(a)

a


In [7]:
class A:
    def __init__(self,m1,m2):
        self.m1=m1
        self.m2=m2
    def __gt__(self,other):   # operators overloading
        m1=self.m1+self.m2
        m2=other.m1+other.m2
        if(m1>m2):
            return True
        else:
            return False

a=A(100,2000)
ab=A(200,100) 
if a>ab:   #------->>bec a and ab are the refernce of class A.and inside class A we dont have the method > greater than, because greater than is a method inside the class int.so
    ###---------->>>>>>>> so to take the method in our classes we have to do operators overloading
    print("a is greater")
else:
    print("b is greater")

a is greater


# printing multiple time string,list and tuple,, wecannot perform slicing and multiple time printing method on set and on dictionary

In [74]:
2*"string"   # --->printing multiple time string

'stringstring'

In [75]:
2*[1,2,3]  # multiple time list

[1, 2, 3, 1, 2, 3]

In [76]:
2*(1,2,3,4)  # multiple time tuple

(1, 2, 3, 4, 1, 2, 3, 4)

# how to define 1 value inside the tuple

In [82]:
a=(1,)   # this is how the 1 value inside the tuple will define
type(a)

tuple

In [81]:
print(a)

(1,)


In [16]:
def c(**a):
    print(a)
    for i,j in a.items():
        if(i=='surname'):
            break
        print(i,j)


In [17]:
c(customer_d='1',name='deepak',surname='khetwal')

{'customer_d': '1', 'name': 'deepak', 'surname': 'khetwal'}
customer_d 1
name deepak


In [2]:
for i in range(0,5):
    for j in range(i+1,5):
        print(j,end="")

    print()
        

1234
234
34
4



In [6]:
for i in range(1,5):
    t=i
    for j in range(1,8):
        if (i==1):
            if(j==4):
                print(i,end=' ')
            else:
                print(' ',end=' ')
        else:
            if(j>=5-i and j<=3+i):
                if(j>=1 and j>=4):
                    print(t,end=' ')
                    t=t+1  
                
                else:
                    print(t,end=' ')
                    t=t-1
            else:
                print(' ',end=' ')
    print(' ')

      1        
    2 1 2      
  3 2 1 2 3    
4 3 2 1 2 3 4  


In [13]:
for i in range(1,5):
    for j in range(1,8):
        if (i>=j):
                print(j,end=' ')
    
        else:
            print(' ',end=' ')
    print(' ')

1              
1 2            
1 2 3          
1 2 3 4        


In [16]:
t=4
for i in range(1,5):
    k=i
    for j in range(1,5):
        if(j>=t):
            print(k,end=' ')
            k=k-1
        else:
            print(' ',end=' ')
    print(' ')
    t=t-1
        

      1  
    2 1  
  3 2 1  
4 3 2 1  


In [ ]:
# hackwer rank solve problem with the help of function

In [27]:
def fun(res):
    
    print(res)
    
    # abhi duplicate nikalunga,as we know how to remove duplicates from the list,using dict funtion
       
    res12=dict.fromkeys(res)
    #print(res12)
    #now again convert dictionary to list
    res1=list(res12)    
    print(res1)
    k=len(res1)-2  # res=list aya  ::::   [1,2,2,3,4,45]-2
    return res1[k]
    

In [28]:
a=[1,4,2,45,2,3,59]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if(a[i]>a[j]):
            temp=a[j]
            a[j]=a[i]
            a[i]=temp
print(a)
# but agar duplicate higa toh duplicate value remove karenebe na,q ki duplicate remove nhi kia toh,fir 2 highest mai prbl higa
# wah mai ek function ke andar karunga
result=fun(a)
print(result)

[1, 2, 2, 3, 4, 45, 59]
[1, 2, 2, 3, 4, 45, 59]
[1, 2, 3, 4, 45, 59]
45


In [33]:
for i in range(1,6):
    for j in range(1,10):
        if(i==1):
            if(j==5):
                print("c",end="")
            else:
                print("-",end="")
        else:
            if(i%2==0):
                if(j%2!=0 and j>i and j<=9-i):
                    print("c",end="")
                else:
                    print("-",end="")
            else:
                if(j%2!=0):
                    print("c",end="")
                
                else:
                    print("-",end="")
    print()

----c----
--c-c-c--
c-c-c-c-c
----c----
c-c-c-c-c
