# simply we have 3 different type by which we can copy 2 array
#1 simplest way:a=[1,2,3]  :b=a   #by this way we can copy one array to another array but the problem is the addres or the location of the array will be same
#2 shallow copy ,dependent array,:for that use view()funtion.but the prbl is one array will be depedent on another array,n both address wil be different
#3 deep copy.independentarray: copy()function is used for this.in this both array will be independent.mean i make any change on one array it wil not affect the second

# simple example we have a array we have to add 5 to each

In [2]:
# kabhi kisi ney bola ki maine ek list dia hai , n tu ek naya list bna n haar value mai apna 5 ,5 extra add kar
# so hum direct for loopmai v kar skate hai
from numpy import *
a=array([1,2,3,4,5])   # adding 5 value to each number
###########@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
for i in a+5:   ####     only possible in numpy
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$4$
    print(i)

6
7
8
9
10


In [45]:
# ##########################     simply we can add
#this happen only in numpy package
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

from numpy import *
a=array([1,2,3,4,5])
a=a+5   # simplest way to add
print(a)

[ 6  7  8  9 10]


In [2]:
# adding two array
from numpy import *
a=array([1,2,3,4])
b=array([34,2,3,4])
c=a+b
print(c)   #simply we canadd 2 array

[35  4  6  8]


In [3]:
# if we have a array and we want the sum of array ,we can directly call the sum function,it is in numpy.num it mean number

# some function in a array.

In [48]:
c=array([35,  4,  6,  8])
print(sum(c))  # as we got the sum of all number inside the sum

53


In [49]:
print(min(c))   #

4


In [50]:
print(max(c))

35


In [51]:
print(sorted(c)) # to get in sorted form

[4, 6, 8, 35]


# we can concatenate two array
#simply by calling concatenate function

In [4]:
print(concatenate([a,b]))     # as we can concatenate two array,means both the array wil join and form a single big array

[ 1  2  3  4 34  2  3  4]


# copy one array to another

In [53]:
from numpy import *
arr1=array([1,2,3,4])
arr2=arr1    # easiest way to copy one array value to another array
print(arr1)
print(arr2)

[1 2 3 4]
[1 2 3 4]


# # idar copy toh huwa but donu array ka location ekhi hai.so ek hi object bana array ka

In [54]:
#but by using above crieteria the both variable will we in the stored in the same address
# as we know the data hold the same value ,are stored in the sme address
print(id(arr1))
print(id(arr2))

63760048
63760048


# but if we want different address for both array  # use a function name is view

In [55]:
from numpy import *
arr1=array([1,2,3,4])
arr2=arr1.view()    # using view function w can copy one array to another but if different location
print(arr1)
print(arr2)
print(id(arr1))   
print(id(arr2))

[1 2 3 4]
[1 2 3 4]
63758808
63759208


# there are two different way by which we caN COPY the array
#1) SHALLOW
#2)DEEP

#SHALLOW=ONE ARRAY IS DEPENDENT ON ANOTHER ARRAY
#2)DEEP=BOTH ARRAY ARE INDEPENDENT

# SHALLOW

In [1]:
from numpy import *
a=array([1,2,3,4])
b=a.view()  
print(id(a))  # both having  A different id
print(id(b))     #both having  A different id
print(a)
print(b)

53755680
53755720
[1 2 3 4]
[1 2 3 4]


# if i change the value in any of the array ,it will effect the both array

In [38]:
b[2]=5      #ek array mai change kia toh donu array mai changes huwa
print(a)    # dekha donu mai changes huwa
print(b)

[1 2 5 4]
[1 2 5 4]


# DEEP COPY

# FOR THIS WE WILL USE THE FUNCTION NAME COPY.SO BY USING THIS FUNCTION NAME,we will get the copy ,n both the array will be independt to each other

In [39]:
# so if i make any change to array .it will not effect the second array
from numpy import *
d1=array([1,2,3,4])
d2=d1.copy()

In [42]:
d2[1]=5   # look i make change in the d2 array 1 index so it only affect the 2 nd array not the first
print(d1)
print(d2)

[1 2 3 4]
[1 5 3 4]


In [9]:
from numpy import *
a=array([1,2,3,4])
b=a.copy()
print(b)
print(id(a)) # id wil be different but both will be dependent
print(id(b))

[1 2 3 4]
67550048
58487616


In [10]:
a[2]=20
print(a)  # a ka change huwa b mai nhi
print(b)

[ 1  2 20  4]
[1 2 3 4]


[12.   3.4  4.   5. ]


In [14]:
from array import *  # this took place inside the array package
a=array('i',[1,2,3,4])
b=array(a.typecode,[b for b in a])
print(b)

array('i', [1, 2, 3, 4])


In [17]:
b[1]=10
print(a)
print(b)

array('i', [1, 2, 3, 4])
array('i', [1, 10, 3, 4])


In [5]:
from numpy import *
a=array([1,2,3,4])
a1=a+4

In [6]:
print(a1)

[5 6 7 8]


In [6]:
from numpy import *
a=array([1,2,3,4])
for i in a+10: #  this is only perform in a numpy
    print(i)

11
12
13
14


In [31]:
from numpy import *
a=array([20,30,40,50])  # array  in a numpy
#  $$$$$$------->>>>>>>>  this only perform on numpy array  <<<<<<<<<<<<<<<<<#$$$$$######
a=a+20

In [32]:
print(a)

[40 50 60 70]


In [33]:
b=a.copy()
# view is a method inside the numpy package of array class 
print(b)


[40 50 60 70]
